### PR TITLE
Add jboss_batch and other misc. fixes

### PR DESCRIPTION
**Pull request by itewk**
Primarily this pull request is to merge in the jboss_batch type.

This also has a couple other small changes that a customer has been running locally and would like to push up stream. Not all are the most ideal fix but they are needed for the module to run and longer term fixes can be decided upon and implemented at a later time.

### CODE REVIEW

**Comment by itewk** [comment]
added two more fixes to this pull request.

@cpitman can we try to merge this soon?

**Comment by itewk** [comment]
@cpitman I'll buy you cookies if you can take some time to merge this in :)

**Comment by itewk** [comment]
@cpitman added a fix for #56

**Comment by itewk** [comment]
@cpitman added a fix based on use.

**Comment by itewk** [comment]
@cpitman  added ability to time out all CLI calls

**Comment by itewk** [comment]
@cpitman any status on reviewing this?

**Comment by itewk** [comment]
@cpitman  bump?

**Comment by cpitman** [comment]
Starting on this now. Either comments or merged by end of day.

**Comment by itewk** [comment]
Thanks a bunch! Let me know if you need to pick my brain on any of this.

**Comment by cpitman** [comment]
@itewk What was the issue with the generator that required the custom resources, just so I understand?

**Comment by cpitman** [comment]
Actually, I should have just scrolled further. Mostly issues around documentation generation.

**Comment by cpitman** [comment]
I need to rebuild my test environment. In the meantime, I made a few small changes and pushed branch jboss_batch. Do these look ok to you?

**Pull request merged**
