### PR TITLE
Issue #66 - add ability to disable restart/cleanup

### PR DESCRIPTION
**Pull request by itewk**
@cpitman how does this look?

### CODE REVIEW

**Comment by itewk** [comment]
@cpitman can this get in before next Wednesday 4/29/15?

**Comment by cpitman** [comment]
I think I would prefer if `server.pp` conditionally declared the cleanup resource instead of passing noop into it, and calling the parameter `manage_server_restart`. What do you think?

**Comment by itewk** [comment]
@cpitman, that could be fine on that side, but I would still like the $noop param to be added to cleanup and passed to its sub resources.

I want/need to be able to do

JBoss_admin::Cleanup <| server = $server_name |> {
  noop => $disable,
}

so I can guaranty no cleanups run. I for instance declare another cleanup to run for artifact deployments. And if I just wrap that in an if then it breaks all of the require and before statements on my other resources to make sure they run after my specfiic cleanup.

And do to a bug in puppet, at least the version I am running, even though meta params are supposed to pass to the sub resources of a defined type, in practice they don't unless you do what I did.

**Comment by cpitman** [comment]
Ok, I understand why you need `noop` in `Cleanup`. I would still prefer the changes I suggested to server.pp.

**Comment by itewk** [comment]
@cpitman alright, ill update shortly.

**Comment by itewk** [comment]
@cpitman hows abouts thats? I han haz mergz?

**Comment by itewk** [comment]
@cpitman thanks a bunch!

**Pull request merged**
